;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_sleep
	.import		_clrscr
	.import		_bgcolor
	.import		_text
	.export		_i
	.export		_main

.segment	"DATA"

_i:
	.word	$0000

.segment	"RODATA"

L003B:
	.byte	$25,$73,$9B,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; bgcolor(COLOR_BLACK); // set the background color
;
	lda     #$00
	jsr     _bgcolor
;
; POKEW(710,192);  // set text color.  710 is memory address for color reg # 2.  
;
	ldx     #$00
	lda     #$C0
	sta     $02C6
	stx     $02C6+1
;
; clrscr();  // clear the screen
;
	jsr     _clrscr
;
; for (i = 0; i <= 254; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L0030:	lda     _i
	cmp     #$FF
	lda     _i+1
	sbc     #$00
	bvc     L0037
	eor     #$80
L0037:	asl     a
	lda     #$00
	tax
	bcc     L0042
;
; printf("%s\n", text);
;
	lda     #<(L003B)
	ldx     #>(L003B)
	jsr     pushax
	lda     #<(_text)
	ldx     #>(_text)
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; sleep(1);   // x seconds
;
	ldx     #$00
	lda     #$01
	jsr     _sleep
;
; for (i = 0; i <= 254; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0039
	inx
L0039:	sta     _i
	stx     _i+1
	jmp     L0030
;
; }
;
L0042:	rts

.endproc

